---
name: CI/CD

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER}}
          password: ${{ secrets.RECIPE_API_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose -f docker-compose.yml run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose -f docker-compose.yml run --rm app sh -c "flake8"
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-20.04
    needs: test-lint  # Runs only after 'test-lint' completes successfully
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOYMENT_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          git clone git@github.com:ShaoNingHuang/receipe-app-api.git
          cd /receipe-app-api
          docker-compose -f docker-compose-deploy.yml down
          docker-compose -f docker-compose-deploy.yml up -d --build
          EOF

